name-template: 'v$RESOLVED_VERSION 🎶'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🎸 Features'
    labels:
      - 'feature'
      - 'enhancement'
    collapse-after: 15
  - title: '❄ Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🤖 Maintenance'
    labels:
      - 'chore'
      - 'documentation'
  - title: '🎼 Other Changes'
    labels:
      - '*'

autolabeler:
  - labels: 'feature'
    title:
      - '/feature/i'
      - '/component/i'
      - '/create/i'
  - labels: 'fix'
    title:
      - '/fix/i'
      - '/bug/i'
  - labels: 'chore'
    title:
      - '/document/i'
      - '/refactor/i'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes

  $CHANGES
