# .github/workflows/pr-labeling.yml
name: PR prsk labeling

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-character-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and add character label with random encounter
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');

            // モジュールを読み込んでCommonJS形式に変換
            function loadModule(filename) {
              const moduleCode = fs.readFileSync(
                path.join(process.env.GITHUB_WORKSPACE, '.github/script', filename),
                'utf8'
              );
              
              // ESモジュールのexportをCommonJS形式に変換
              const convertedCode = moduleCode
                .replace(/export const /g, 'exports.')
                .replace(/export function /g, 'exports.')
                .replace(/export async function /g, 'exports.')
                .replace(/import .+ from ['"]\.\/(.+)['"];?/g, ''); // import文を削除
              
              const module = { exports: {} };
              const func = new Function('module', 'exports', convertedCode);
              func(module, module.exports);
              return module.exports;
            }

            // prsk-yell-label.constants.jsを先に読み込み
            const constants = loadModule('prsk-yell-label.constants.js');

            // prsk-labeling-logic.jsを読み込み
            const logicCode = fs.readFileSync(
              path.join(process.env.GITHUB_WORKSPACE, '.github/script/prsk-labeling-logic.js'),
              'utf8'
            );

            // import文を削除し、定数への参照を置き換え
            const convertedLogicCode = logicCode
              .replace(/import .+ from ['"]\.\/prsk-yell-label\.constants['"];?/g, '')
              .replace(/export const /g, 'exports.')
              .replace(/export function /g, 'exports.')
              .replace(/export async function /g, 'exports.')
              .replace(/\bprskCharacter\b/g, 'constants.prskCharacter')
              .replace(/\bvocaloidCharacter\b/g, 'constants.vocaloidCharacter')
              .replace(/\bcollaborationScenarios\b/g, 'constants.collaborationScenarios')
              .replace(/\breplaceTemplate\b/g, 'constants.replaceTemplate');

            const logicModule = { exports: {} };
            const logicFunc = new Function('module', 'exports', 'constants', convertedLogicCode);
            logicFunc(logicModule, logicModule.exports, constants);

            // メイン処理を実行
            await logicModule.exports.handlePrLabeling(github, context);
