# .github/workflows/pr-labeling.yml
name: PR prsk labeling

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-character-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and add character label with random encounter
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');

            // 定数ファイルを読み込み
            const constantsCode = fs.readFileSync(
              path.join(process.env.GITHUB_WORKSPACE, '.github/script/prsk-yell-label.constants.js'),
              'utf8'
            );

            // export文を削除してオブジェクトとして評価
            const cleanedConstants = constantsCode
              .replace(/export const /g, 'const ')
              .replace(/export function /g, 'function ');

            // 定数を評価
            eval(cleanedConstants);

            // ロジックファイルを読み込み
            const logicCode = fs.readFileSync(
              path.join(process.env.GITHUB_WORKSPACE, '.github/script/prsk-labeling-logic.js'),
              'utf8'
            );

            // import文を削除してexport文を削除
            const cleanedLogic = logicCode
              .replace(/import\s+{[^}]+}\s+from\s+['"][^'"]+['"];?/g, '')
              .replace(/export const /g, 'const ')
              .replace(/export function /g, 'function ')
              .replace(/export async function /g, 'async function ');

            // ロジックを評価
            eval(cleanedLogic);

            // メイン処理を実行
            await handlePrLabeling(github, context);
