# .github/workflows/pr-labeling.yml
name: PR prsk labeling

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  add-prsk-character-label:
    uses: Narumikr/sekai-network/.github/workflows/prsk-labeling.yaml@main
